server:
  port: 8080
spring:
  application:
    name: spring-cloud
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 8719
      filter:
        enabled: false
      eager: false
      enabled: true
